version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/snx-api
hooks:
  ApplicationStop:
    - location: scripts/app-stop.sh
      timeout: 360
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 180
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 180
  ValidateService:
    - location: scripts/validate.sh
      timeout: 600
