# syntax=docker/dockerfile:1
FROM synthetixio/docker-node:20.12-ubuntu as builder

RUN mkdir /app
WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --prefer-offline
COPY . .

FROM builder as api
USER node
ENV CACHE_TIME 1
EXPOSE 3000
CMD ["pnpm", "docker:dev"]
