# syntax=docker/dockerfile:1
FROM synthetixio/docker-node:18.13-alpine as builder

RUN mkdir /app
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn --frozen-lockfile --prefer-offline --no-audit
COPY . .

FROM builder as api
USER node
ENV CACHE_TIME 1
EXPOSE 3000
CMD ["yarn", "docker:dev"]
