version: '3.9'

services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    env_file:
      - api.env
    ports:
      - 3000:3000
    depends_on:
      - cache
    networks:
      - api

  cache:
    container_name: cache
    image: redis:7.0.10-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_HOST_PASSWORD"
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_REPLICATION_MODE=master
    env_file:
      - redis.env
    networks:
      - api

  proxy:
    container_name: proxy
    image: synthetixio/nginx-debug:d294126f4b4f41d99538217ce68f2e8e9bfcc6fd-base
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/scripts/setup-whitelist.sh:/docker-entrypoint.d/setup-whitelist.sh
    ports:
      - 3001:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - SNX_API_PROXY_URL=http://api:3000
      - DEBT_POOL_COMP_PROXY_URL=http://host.docker.internal:3002/
      - STAKING_RATIO_PROXY_URL=http://host.docker.internal:3001/
      - PYTH_MAINNET_PROXY_URL=http://host.docker.internal:4200/api/
      - PYTH_TESTNET_PROXY_URL=http://host.docker.internal:4200/api/
    env_file:
      - nginx.env
    depends_on:
      - api
    networks:
      - api
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  api:
