version: '3.9'

x-logging:
  &default-logging
  driver: awslogs
  options:
    mode: non-blocking
    awslogs-region: us-east-1
    awslogs-group: snx-api-prod
    awslogs-create-group: "true"
    tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}/{{.Name}}/{{.ID}}'

services:
  api:
    container_name: api
    restart: unless-stopped
    build: .
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    env_file:
      - api.env
    ports:
      - 3000:3000
    depends_on:
      - cache
    networks:
      - api
    logging: *default-logging

  cache:
    container_name: cache
    image: redis:7.0.7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_HOST_PASSWORD"
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_REPLICATION_MODE=master
    env_file:
      - redis.env
    networks:
      - api
    logging: *default-logging

  proxy:
    container_name: proxy
    image: nginx:1.23.3-alpine-slim
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PROXY_URL=http://api:3000
    depends_on:
      - api
    networks:
      - api
    logging: *default-logging

networks:
  api:
